blastdb:
	mkdir -p data/blastdb
	wget ftp://ftp.wwpdb.org/pub/pdb/derived_data/pdb_seqres.txt.gz -O data/blastdb/pdb_seqres.txt.gz
	cd data/blastdb && gunzip -f pdb_seqres.txt.gz && \
	makeblastdb -in pdb_seqres.txt -out pdbseqres -dbtype prot	
	rm -rf data/pdb_seqres.txt


download_pdb:
	# WARNING: Downloading and extracting the pdb requires more than 100GB
	mkdir -p data/pdb_rsync
	mkdir -p data/pdb
	rsync -rlpt -v -z --delete --port=33444 \
		rsync.wwpdb.org::ftp_data/structures/divided/pdb/ data/pdb_rsync/
	cp -r data/pdb_rsync/* data/pdb/
	gunzip -r data/pdb/


torsions:
	cc -o libs/torsions libs/torsions.c -lm


torsions_db: torsions
	bash -i -c "source env/bin/activate && python -m cref.utils.cache_torsions data/pdb data/torsions.db"


scratch:
	mkdir libs
	cd libs && wget http://download.igb.uci.edu/SCRATCH-1D_1.0.tar.gz
	cd libs && tar xvzf SCRATCH-1D_1.0.tar.gz
	cd libs/SCRATCH-1D_1.0 && perl install.pl


peptide:
	git clone https://github.com/mchelem/peptide


python_packages:
	virtualenv --python=/usr/bin/python3.5 env
	bash -i -c "source env/bin/activate && pip install pip --upgrade"
	bash -i -c "source env/bin/activate && pip install -r requirements.txt"
	bash -i -c "source env/bin/activate && pip install git+https://github.com/mchelem/porter_paleale"


server_packages:
	# Only required when interfacing with the wCReF interface
	sudo apt-get install -y rabbitmq-server


packages:
	sudo apt-get install -y git # Required to install pip packages from github
	sudo apt-get install -y tcl8.4-dev tk8.4-dev # Required to generate ramachandram plots
	sudo apt-get install -y liblapack-dev gcc gfortran # Required by numpy
	sudo apt-get install -y ncbi-blast+ # Required to make sequence alignments
	sudo apt-get install -y python3.5 python3.5-dev python3.5-tk python-virtualenv # Basic python env


ss_db:
	wget http://www.rcsb.org/pdb/files/ss.txt.gz -O data/ss.txt.gz
	cd data && gunzip -f ss.txt.gz
	bash -i -c "source env/bin/activate && python -m cref.utils.import_pdb_ss data/ss.txt data/ss.db"
	rm -rf data/ss.txt

precomputed_structure_databases:
	# Downloads precomputed secondary structure database
	# Can be generated by running "make ss_db"
	wget https://www.dropbox.com/s/xb7qc49p75k9qlf/ss.db.tgz?dl=0 -O ss.db.tgz
	gunzip -f ss.db.gz
	# Downloads precomputed torsions database
	# Can be generated by running "make download_pdb && make torsions_db"
	# WARNING: Downloading and extracting the pdb requires more than 100GB
	wget https://www.dropbox.com/s/18q2t35eh6rml1s/torsions.db.tgz?dl=0 -O torsions.db.tgz
	gunzip -f torsions.db.gz

databases: blastdb precomputed_structure_databases


install: packages python_packages peptide torsions scratch databases
	mkdir -p predictions

coverage:
	bash -i -c "source env/bin/activate && coverage run --source=cref -m unittest discover"
	coverage html
	coverage report
